### ISSUE TITLE
Errors while loading the module

### ISSUE THREAD

**Issue by Brand-dev** [BG-Software-LLC/SSB-DiscordStatistics#2]
hi this addons just dont work in 1.18.1

**Comment by OmerBenGera** [comment]
Errors? Something?
This is not a valid bug report.

**Comment by Brand-dev** [comment]
When i start the server with default config , addons load, but when i put a token for my bot (same of discordsrv) addons just dont load.

No error nothing! Idk how to make an issue report if i dont have any error or wtv.....

**Comment by OmerBenGera** [comment]
> When i start the server with default config , addons load, but when i put a token for my bot (same of discordsrv) addons just dont load.
> 
> No error nothing! Idk how to make an issue report if i dont have any error or wtv.....

What do you mean that they don't load?
Mind uploading your logs file?

**Comment by Brand-dev** [comment]
Addon juste dont load ..... no error nothing nothing nothing !!!!!!!

**Comment by OmerBenGera** [comment]
> Addon juste dont load ..... no error nothing nothing nothing !!!!!!!

Weird.
Mind uploading your logs file to pastebin and send it here?

**Comment by Brand-dev** [comment]
https://www.toptal.com/developers/hastebin/sakipumoko.md

**Comment by OmerBenGera** [comment]
You changed the admin's role name to something else - update it on the module's config as well.

**Comment by Brand-dev** [comment]
No config for that in the config.....

**Comment by OmerBenGera** [comment]
Right, my bad.
Looking into it right now.

**Comment by OmerBenGera** [comment]
Fixed in latest dev build

**Comment by Brand-dev** [comment]
https://www.toptal.com/developers/hastebin/tedidirara.md
....

**Comment by OmerBenGera** [comment]
Check out latest build, it should be fixed.
